[project]
name = "roblox-mcp-server"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "fastmcp>=2.10.5",
    "keyring>=25.6.0",
    "roblox>=2.0.0",
    "tk>=0.1.0",
]
